name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

env:
  OCI_URL: ghcr.io/openmcp-project

jobs:
  release_tag:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        id: app-token
        with:
          # required
          app-id: 1312871
          private-key: ${{ secrets.OPENMCP_CI_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read and validate VERSION
        id: version
        run: |
          VERSION=$(task version)
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-dev(-[0-9a-f]*)?)?$ ]]; then
            echo "Invalid version format: $VERSION"
            exit 1
          fi
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Skip release if version is a dev version
        if: contains(env.version, '-dev')
        run: |
          echo "Skipping development version release: ${{ env.version }}"
          echo "SKIP=true" >> $GITHUB_ENV
          exit 0

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      # - name: Set up Docker Context for Buildx
      #   id: buildx-context
      #   run: |
      #     docker context create builders

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   timeout-minutes: 5
      #   uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      #   with:
      #     version: latest

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: Cross Build
        run: |
          PROJECT_ROOT=$(pwd)
          echo "Using /mnt $(ls -la /mnt)"
          WORK_DIR="/mnt/dist"
          echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV
          sudo mkdir -p ${WORK_DIR}
          sudo chmod 777 ${WORK_DIR}
          echo "work dir: ${WORK_DIR}, free space: $(df -h ${WORK_DIR} | tail -1 | awk '{print $4}')"

          build_matrix=("linux,amd64" "linux,arm64" "darwin,amd64" "darwin,arm64", "windows,amd64")

          for i in "${build_matrix[@]}"; do
            IFS=',' read os arch <<< "${i}"

            echo "Building $os/$arch version ${{ env.version}}..."
            bin_path="${WORK_DIR}/landscapercli-$os-$arch"

            cd "$PROJECT_ROOT"

            CGO_ENABLED=0 GOOS=$os GOARCH=$arch GO111MODULE=on \
            go build -o $bin_path \
            -ldflags "-s -w \
                      -X github.com/openmcp-project/landscapercli/pkg/version.LandscaperCliVersion=${{ env.version }} \
                      -X github.com/openmcp-project/landscapercli/pkg/version.gitTreeState=$([ -z git status --porcelain 2>/dev/null ] && echo clean || echo dirty) \
                      -X github.com/openmcp-project/landscapercli/pkg/version.gitCommit=$(git rev-parse --verify HEAD)" \
            ${PROJECT_ROOT}/cmd/landscapercli

            # create zipped file
            cd "${WORK_DIR}"
            gzip -f "$bin_path"
            # -f --force           force overwriting & compress links
            # -k --keep            don't delete input files during operation
          done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          # Artifact name
          # name: # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.WORK_DIR }}/*.gz
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error # optional, default is warn
          # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
          compression-level: 0 # optional, default is 6
          # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.
          overwrite: false # optional, default is false
          # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.
          include-hidden-files: false # optional, default is false
          
      - name: Build and Push OCM Component
        run: |
          task build:ocm:all --verbose
